# Generated by Django 4.2.16 on 2024-12-17 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='buyer',
        ),
    ]
