# Generated by Django 4.2.16 on 2024-11-26 14:46

from django.db import migrations, models
import django.db.models.deletion
import shopping.models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_alter_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20, verbose_name=shopping.models.OrderStatus)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shopping.cartitem')),
            ],
        ),
    ]
